import { Geist, Geist_Mono } from "next/font/google";
import BarbaController from "@/utils/BarbaController";
import "./globals.css";
import Loader from "@/components/globals/Loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const uiSecret = process.env.UI_PROTECTION_KEY ?? "dev-key";

  return (
    <html lang="en">
      <body>
        <BarbaController />
        <Loader secretKey={uiSecret} />
        <div id="barba-wrapper" data-barba="wrapper">
          {children}
        </div>
      </body>
    </html>
  );
}